name: Official Tests

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  run_tests:
    name: "🛡️ ${{ matrix.name }}"
    uses: "./.github/workflows/test.yml"
    with:
      name: ${{ matrix.name }}
      driverRepoUrl: ${{ matrix.driverRepoUrl }}
      driverRepoBranch: ${{ matrix.driverRepoBranch }}
      php: ${{ matrix.php }}
      setUpCmd: ${{ matrix.setUpCmd }}
      testCmd: ${{ matrix.testCmd }}
      tearDownCmd: ${{ matrix.tearDownCmd }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "BrowserKit (http client)"
            driverRepoUrl: "https://github.com/minkphp/MinkBrowserKitDriver.git"
            driverRepoBranch: "master"
            php: "7.2"
            # language=bash
            testCmd: ./vendor/bin/phpunit --colors=always --testdox --configuration ./phpunit.http_client.xml

          - name: "BrowserKit (http kernel)"
            driverRepoUrl: "https://github.com/minkphp/MinkBrowserKitDriver.git"
            driverRepoBranch: "master"
            php: "7.2"
            # language=bash
            testCmd: ./vendor/bin/phpunit --colors=always --testdox

          - name: "Selenium2"
            driverRepoUrl: "https://github.com/minkphp/MinkSelenium2Driver.git"
            driverRepoBranch: "master"
            php: "7.2"
            # language=bash
            setUpCmd: |
              export SELENIUM_IMAGE=selenium/standalone-firefox:2.53.1
              docker compose up --wait --quiet-pull
              curl --retry 5 --retry-all-errors --retry-delay 1 --max-time 10 --head -X GET http://localhost:4444/wd/hub/status
            # language=bash
            testCmd: |
              export WEB_FIXTURES_BROWSER=firefox
              export SELENIUM_VERSION=2.53.1
              export DRIVER_MACHINE_BASE_PATH=/fixtures/
              export WEB_FIXTURES_HOST=http://host.docker.internal:8002
              ./vendor/bin/phpunit --colors=always --testdox
            # language=bash
            tearDownCmd: |
              docker compose logs --no-color --no-log-prefix --timestamps selenium &> ./logs/selenium.docker.log

          - name: "WebDriver-Classic"
            driverRepoUrl: "https://github.com/minkphp/webdriver-classic-driver.git"
            driverRepoBranch: "main"
            php: "7.4"
            # language=bash
            setUpCmd: |
              export SELENIUM_IMAGE=selenium/standalone-firefox:4
              docker compose up --wait --quiet-pull
              curl --retry 5 --retry-all-errors --retry-delay 1 --max-time 10 --head -X GET http://localhost:4444/wd/hub/status
            # language=bash
            testCmd: |
              export WEB_FIXTURES_BROWSER=firefox
              export DRIVER_MACHINE_BASE_PATH=/fixtures/
              export WEB_FIXTURES_HOST=http://host.docker.internal:8002
              ./vendor/bin/phpunit --colors=always --testdox
            # language=bash
            tearDownCmd: |
              docker compose logs --no-color --no-log-prefix --timestamps selenium &> ./logs/selenium.docker.log
